// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCKFNziuuP3O4EdCZ0QseKrhRewWJGSPzo',
    appId: '1:939584464679:web:fa71cd49ebaf5901d8eb02',
    messagingSenderId: '939584464679',
    projectId: 'flutter-refresher-b7fae',
    authDomain: 'flutter-refresher-b7fae.firebaseapp.com',
    storageBucket: 'flutter-refresher-b7fae.firebasestorage.app',
    measurementId: 'G-G6ZZ3PFWXS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCZfVARiUGoCcaq7_OUYIwjpcLskD5NLDQ',
    appId: '1:939584464679:android:ae8c206f10bf1179d8eb02',
    messagingSenderId: '939584464679',
    projectId: 'flutter-refresher-b7fae',
    storageBucket: 'flutter-refresher-b7fae.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAfUJuV_o4OIZ5e6Q2bwgA_Wy9cQro9CqE',
    appId: '1:939584464679:ios:cfc73a0bcd243184d8eb02',
    messagingSenderId: '939584464679',
    projectId: 'flutter-refresher-b7fae',
    storageBucket: 'flutter-refresher-b7fae.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAfUJuV_o4OIZ5e6Q2bwgA_Wy9cQro9CqE',
    appId: '1:939584464679:ios:cfc73a0bcd243184d8eb02',
    messagingSenderId: '939584464679',
    projectId: 'flutter-refresher-b7fae',
    storageBucket: 'flutter-refresher-b7fae.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCKFNziuuP3O4EdCZ0QseKrhRewWJGSPzo',
    appId: '1:939584464679:web:1606b2f1cdf75c3bd8eb02',
    messagingSenderId: '939584464679',
    projectId: 'flutter-refresher-b7fae',
    authDomain: 'flutter-refresher-b7fae.firebaseapp.com',
    storageBucket: 'flutter-refresher-b7fae.firebasestorage.app',
    measurementId: 'G-GYMSSMCT9R',
  );
}
